version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart:
      always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    command: docker wait db [db]
    environment:
      WAIT_HOSTS: db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/berloga?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: black
      SPRING_DATASOURCE_PASSWORD: Black1982@
    networks:
      - backend
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_DATABASE: berloga
      MYSQL_USER: black
      MYSQL_PASSWORD: Black1982@
      MYSQL_ROOT_PASSWORD: root
      container_name: "db"
    healthcheck:
      test: mysqladmin -uroot -ppassword ping
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - /var/lib/mysql
    networks:
      - backend

    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8

volumes:
  db:
networks:
  backend:


